name: Daily Quest Reset

on:
  schedule:
    - cron: "0 5 * * *" # 12:00 AM EST (adjust if needed)
  workflow_dispatch: # Allows manual run

jobs:
  reset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Daily Quest Reset
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DAILY_QUESTS_DB: ${{ secrets.DAILY_QUESTS_DB }}
        run: node systems/resetDailyQuests.js
